// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://avumhsstmcyvqyypudku.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF2dW1oc3N0bWN5dnF5eXB1ZGt1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyMDA1NTAsImV4cCI6MjA3MDc3NjU1MH0.fSydRgdFB2P9GTY_83QmPNi5j0jmesB2fFwJMo6M8gs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});